
language: node_js
node_js:
  - "10"

env:
  - NODE_PACKAGE=driver
  - NODE_PACKAGE=finder

install:
  - cd $NODE_PACKAGE
  - npm --version
  - node --version
  - npm i

script:
  - npm run lint
  - npm publish --dry-run
  - npm test
