name: Python

on:
  workflow_dispatch:
  push:
    paths:
      - 'finder/python/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'finder/python/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest Appium-Python-Client
    - name: Analyzing the code with pylint
      run: |
        cd finder/python
        pylint tests/ appium_flutter_finder/
    - name: Run tests
      run: |
        cd finder/python
        pytest tests/**
