# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: driver
      - run: npm test
        working-directory: driver

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: driver
      - name: run
        working-directory: driver
        run: |
          rm npm-shrinkwrap.json
          npm prune --production
          rm -rf node_modules/appium
          npm shrinkwrap
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        working-directory: driver
      - run: npm ci --only=dev
        name: Install dev dependencies for the release
        working-directory: driver
      - run: npx semantic-release --dry-run
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # to make the push failure
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Release
        working-directory: driver
